package graphqls

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"social-media-backend-1/internal/outers/deliveries/graphqls/model"
)

// FindChatMessageByID is the resolver for the findChatMessageByID field.
func (r *entityResolver) FindChatMessageByID(ctx context.Context, id string) (*model.ChatMessage, error) {
	result := &model.ChatMessage{
		ID: id,
	}

	return result, nil
}

// FindChatRoomByID is the resolver for the findChatRoomByID field.
func (r *entityResolver) FindChatRoomByID(ctx context.Context, id string) (*model.ChatRoom, error) {
	result := &model.ChatRoom{
		ID: id,
	}

	return result, nil
}

// FindPostByID is the resolver for the findPostByID field.
func (r *entityResolver) FindPostByID(ctx context.Context, id string) (*model.Post, error) {
	result := &model.Post{
		ID: id,
	}

	return result, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
