// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Email            string         `json:"email"`
	Password         string         `json:"password"`
	TotalPostLike    float64        `json:"totalPostLike"`
	TotalChatMessage float64        `json:"totalChatMessage"`
	Messages         []*ChatMessage `json:"messages,omitempty"`
	Rooms            []*ChatRoom    `json:"rooms,omitempty"`
	Posts            []*Post        `json:"posts,omitempty"`
	PostLikes        []*PostLike    `json:"postLikes,omitempty"`
}

func (Account) IsEntity() {}

type AccountInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type ChatMessage struct {
	ID        string    `json:"id"`
	Content   string    `json:"content"`
	AccountID string    `json:"accountId"`
	Account   *Account  `json:"account"`
	Room      *ChatRoom `json:"room"`
}

func (ChatMessage) IsEntity() {}

type ChatRoom struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Description string            `json:"description"`
	Members     []*ChatRoomMember `json:"members,omitempty"`
	Messages    []*ChatMessage    `json:"messages,omitempty"`
}

func (ChatRoom) IsEntity() {}

type ChatRoomMember struct {
	ID        string    `json:"id"`
	AccountID string    `json:"accountId"`
	Account   *Account  `json:"account"`
	Room      *ChatRoom `json:"room"`
}

func (ChatRoomMember) IsEntity() {}

type Mutation struct {
}

type Post struct {
	ID        string      `json:"id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	AccountID string      `json:"accountId"`
	Account   *Account    `json:"account"`
	Likes     []*PostLike `json:"likes,omitempty"`
}

func (Post) IsEntity() {}

type PostLike struct {
	ID        string   `json:"id"`
	Post      *Post    `json:"post"`
	AccountID string   `json:"accountId"`
	Account   *Account `json:"account"`
}

func (PostLike) IsEntity() {}

type Query struct {
}
