// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	Email            string  `json:"email"`
	Password         string  `json:"password"`
	TotalPostLike    float64 `json:"totalPostLike"`
	TotalChatMessage float64 `json:"totalChatMessage"`
	Posts            []*Post `json:"posts"`
}

type AccountInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type ChatMessage struct {
	ID     string   `json:"id"`
	Sender *Account `json:"sender"`
}

func (ChatMessage) IsEntity() {}

type ChatRoom struct {
	ID           string     `json:"id"`
	Participants []*Account `json:"participants"`
}

func (ChatRoom) IsEntity() {}

type Mutation struct {
}

type Post struct {
	ID     string   `json:"id"`
	Author *Account `json:"author"`
}

func (Post) IsEntity() {}

type Query struct {
}
